[project]
name = "rescue-scripts"
version = "0.1.0"
description = "Whitehat rescue scripts."
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
    "flashbots>=2.0.0",
    "python-dotenv>=1.1.1",
    "web3==6.20.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]
